### PR TITLE
Add linux support for new branch

### PR DESCRIPTION
**Pull request by goose121**
Quick edit to struct.unpack() call allowing Linux version from CTurt/3DSController to interface with the new version, currently does NOT do anything with the volume slider value

### CODE REVIEW

**Comment by Ordinaryperson2** [comment]
Hi, I haven't had time to work with this project lately (in fact I only did anything at all for a few months, and that was over a year ago).
I'd like to get back into it at some point, but I don't know how soon that will be. For now, if you've verified that this works you can post your own build in the thread if you'd like. I think at least a few people would appreciate it.

**Comment by goose121** [comment]
It doesn't even need to be built, seeing as the only changes are to a python script. I'll just link to my version of the repo on the thread and link back to yours for builds

**Comment by Webbeh** [comment]
Oops, I posted a PR without even checking if anyone else did it...
#17 

I added volume control also, sends as uinput's ABS_VOLUME command and is correctly clamped.

**Comment by Ordinaryperson2** [comment]
Sorry I didn't look into this properly at the time, but since Webbeh's implementation sounds more complete I've merged that version.

**Pull request closed without merging**
